# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='field',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
