# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('spicialization_field', models.CharField(choices=[('software', 'software'), ('hardware', 'hardware'), ('marketing', 'marketing'), ('finances', 'finances'), ('other', 'other')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('document', models.FileField(upload_to='mentor_documents')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
