# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=1000, null=True)),
                ('news_para', models.CharField(blank=True, max_length=5000, null=True)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news/news_image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
