# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('committee_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('committee_type', models.CharField(blank=True, choices=[('PROFITABLE', 'profitable'), ('NON-PROFITABLE', 'non-profitable')], max_length=20, null=True)),
                ('last2activities1', models.FileField(upload_to='committee_documents')),
                ('last2activities2', models.FileField(upload_to='committee_documents')),
                ('self_certification', models.FileField(upload_to='committee_documents')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
